docker-build:
  
  #Falls der Runner auf K8S nicht auf tcp anstatt unix sock konfiguriert ist... EVIL!
  # variables:
  #   DOCKER_TLS_CERTDIR: ""
  #   DOCKER_HOST: "tcp://localhost:2375"

  stage: build
  image: docker:git
  services:
    - docker:dind
  
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
  script:
    - sleep 30
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
