apiVersion: v1
kind: Namespace
metadata:
  name: pic-carousel

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: pic-carousel
spec:
  selector:
    matchLabels:
      app: mongodb # has to match .spec.template.metadata.labels
  serviceName: "mongo-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: mongo:4
        ports:
        - containerPort: 27017
          name: mongo-port
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: pic-carousel
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - name: mongo-port
    protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pic-carousel-app
  namespace: pic-carousel
  labels:
    app:  pic-carousel-app
spec:
  selector:
    matchLabels:
      app: pic-carousel-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  pic-carousel-app
    spec:
      containers:
      - name: pic-carousel-app
        image: ghcr.io/alirionx/pic-carousel:latest
        env:
        - name: MONGODB_HOST
          value: mongo-service
        ports:
        - containerPort: 5000
          name: web-port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: pic-carousel
spec:
  selector:
    app: pic-carousel-app
  type: ClusterIP
  # type: LoadBalancer
  ports:
  - name: web-port
    protocol: TCP
    port: 5000
    targetPort: 5000